(list 
(make-instance 'RANK-PLAYER
 :SCORE 386.58 :RANK "1" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 355.38 :RANK "2" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 345.2 :RANK "3" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 336.66 :RANK "4" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 326.16 :RANK "5" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 317.12 :RANK "6" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 309.4 :RANK "7" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 306.18 :RANK "8" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 303.16 :RANK "9" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 291.46 :RANK "10" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 283.46 :RANK "11" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 274.5 :RANK "12" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 266.1 :RANK "13" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 264.6 :RANK "14" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 263.92 :RANK "15" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 262.12 :RANK "16" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 262 :RANK "17" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 261.88 :RANK "18" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 256.52 :RANK "19" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 250.94 :RANK "20" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 250.6 :RANK "21" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 250.42 :RANK "22" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 247 :RANK "23" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 242.8 :RANK "24" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 241.78 :RANK "25" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 237.2 :RANK "26" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 226.4 :RANK "27" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 222.1 :RANK "28" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 218.3 :RANK "29" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 216.8 :RANK "30" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 210.5 :RANK "31" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 210.2 :RANK "32" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 207.4 :RANK "33" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 203.7 :RANK "34" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 203.4 :RANK "35" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 203.4 :RANK "36" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 201.42 :RANK "37" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 201 :RANK "38" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 198.8 :RANK "39" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 196.66 :RANK "40" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 194.1 :RANK "41" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 186.4 :RANK "42" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 184.4 :RANK "43" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 183.8 :RANK "44" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 183.5 :RANK "45" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 179.8 :RANK "46" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 179.4 :RANK "47" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 177.1 :RANK "48" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 175.8 :RANK "49" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 175.4 :RANK "50" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 171.4 :RANK "51" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 169.52 :RANK "52" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 169.4 :RANK "53" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 169.2 :RANK "54" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 165.5 :RANK "55" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 164.5 :RANK "56" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 162.4 :RANK "57" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 162 :RANK "58" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 160.3 :RANK "59" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 158.8 :RANK "60" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 155.8 :RANK "61" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 155.2 :RANK "62" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 154.68 :RANK "63" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 153.6 :RANK "64" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 152.2 :RANK "65" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 151.3 :RANK "66" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 149.4 :RANK "67" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 148.86 :RANK "68" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 145 :RANK "69" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 141.4 :RANK "70" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 141 :RANK "71" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 140.6 :RANK "72" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 140.1 :RANK "73" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 139.9 :RANK "74" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 139.1 :RANK "75" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 138.83061 :RANK "76" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 137.14 :RANK "77" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 135.26 :RANK "78" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 134.4 :RANK "79" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 134.1 :RANK "80" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 133.5 :RANK "81" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 131.70012 :RANK "82" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 131.6 :RANK "83" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 130.3 :RANK "84" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 129.6 :RANK "85" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 128 :RANK "86" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 127.7 :RANK "87" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 125.75803 :RANK "88" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 124.58 :RANK "89" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 121.9 :RANK "90" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 119.2 :RANK "91" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 118.62754 :RANK "92" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 116.8 :RANK "93" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 116.7 :RANK "94" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 116.5 :RANK "95" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 116.5 :RANK "96" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 116.1 :RANK "97" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 116.1 :RANK "98" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 115.4 :RANK "99" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 115.1 :RANK "100" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 114.6 :RANK "101" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 114.5 :RANK "102" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 114.3 :RANK "103" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 114.3 :RANK "104" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 112 :RANK "105" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 111.4 :RANK "106" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 110.8 :RANK "107" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 110.5 :RANK "108" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 108.9 :RANK "109" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 108.7 :RANK "110" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 108 :RANK "111" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 107.9 :RANK "112" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 107.8 :RANK "113" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 107.6 :RANK "114" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 106 :RANK "115" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 105.9 :RANK "116" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 105.3 :RANK "117" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 104.6 :RANK "118" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 104.54 :RANK "119" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 104.28 :RANK "120" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 103.8 :RANK "121" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 103.7 :RANK "122" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 103.3 :RANK "123" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 101.9 :RANK "124" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 100.7 :RANK "125" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 99.1 :RANK "126" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 99.06 :RANK "127" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 98.6 :RANK "128" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 98.1 :RANK "129" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 97 :RANK "130" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 96.4 :RANK "131" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 96.1 :RANK "132" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 95.8 :RANK "133" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 95.1 :RANK "134" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 95 :RANK "135" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 94.85923 :RANK "136" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 94.7 :RANK "137" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 93.2 :RANK "138" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 93.1 :RANK "139" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 93.1 :RANK "140" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 92.6 :RANK "141" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 92 :RANK "142" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 91.7 :RANK "143" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 91.7 :RANK "144" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 90.6 :RANK "145" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 90.10557 :RANK "146" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 90.10557 :RANK "147" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 90 :RANK "148" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 89.4 :RANK "149" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 88.7 :RANK "150" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 88.4 :RANK "151" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 88 :RANK "152" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 88 :RANK "153" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 87.8 :RANK "154" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 87.3 :RANK "155" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 87.2 :RANK "156" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 87.1 :RANK "157" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 86.6 :RANK "158" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 86.36 :RANK "159" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 86 :RANK "160" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 85 :RANK "161" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 85 :RANK "162" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 84.9 :RANK "163" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 84.8 :RANK "164" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 84.6 :RANK "165" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 84.4 :RANK "166" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 83.98 :RANK "167" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 83.8 :RANK "168" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 82.9 :RANK "169" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 82.7 :RANK "170" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 82 :RANK "171" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 81.7 :RANK "172" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 79.4 :RANK "173" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 78.7 :RANK "174" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 78.3 :RANK "175" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 78.22141 :RANK "176" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 78 :RANK "177" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 78 :RANK "178" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 77.4 :RANK "179" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 77.3 :RANK "180" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 77.033 :RANK "181" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 77 :RANK "182" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 76.4 :RANK "183" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 76.3 :RANK "184" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 76 :RANK "185" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 75.9 :RANK "186" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 75 :RANK "187" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 74.7 :RANK "188" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 74.65616 :RANK "189" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 74.4 :RANK "190" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 74 :RANK "191" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 74 :RANK "192" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 72.3 :RANK "193" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 72.1 :RANK "194" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 71.09092 :RANK "195" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 71 :RANK "196" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 71 :RANK "197" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 70.2 :RANK "198" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 70.1 :RANK "199" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 69.2 :RANK "200" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 68.7 :RANK "201" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 68.6 :RANK "202" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 68.3 :RANK "203" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 68.2 :RANK "204" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 68.1 :RANK "205" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 67.6 :RANK "206" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 67.52567 :RANK "207" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 67.5 :RANK "208" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 67.5 :RANK "209" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 65.9 :RANK "210" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 65.6 :RANK "211" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 64.8 :RANK "212" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 64.6 :RANK "213" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 64 :RANK "214" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 64 :RANK "215" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 63.960426 :RANK "216" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 63.9 :RANK "217" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 63.8 :RANK "218" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 63.8 :RANK "219" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 63.2 :RANK "220" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 63 :RANK "221" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 62.3 :RANK "222" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 62 :RANK "223" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 61.4 :RANK "224" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 61.3 :RANK "225" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 61 :RANK "226" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 60.6 :RANK "227" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 60 :RANK "228" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 59.1 :RANK "229" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 59 :RANK "230" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 58.9 :RANK "231" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 58 :RANK "232" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 57.6 :RANK "233" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 57 :RANK "234" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 56.9 :RANK "235" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 56.4 :RANK "236" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 55.9 :RANK "237" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 55.8 :RANK "238" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 55.54 :RANK "239" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 55.1 :RANK "240" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 54.7 :RANK "241" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 54.6 :RANK "242" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 54.5 :RANK "243" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 54.4531 :RANK "244" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 53.9 :RANK "245" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 53.68 :RANK "246" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 53.5 :RANK "247" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 53.3 :RANK "248" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 53 :RANK "249" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 52.4 :RANK "250" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 52.076267 :RANK "251" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 52 :RANK "252" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 51.3 :RANK "253" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 51.2 :RANK "254" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 51.1 :RANK "255" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 51 :RANK "256" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 50.9 :RANK "257" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 50.1 :RANK "258" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 49.699436 :RANK "259" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 49.699436 :RANK "260" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 49.5 :RANK "261" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 48 :RANK "262" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 47.8 :RANK "263" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 47.8 :RANK "264" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 47.6 :RANK "265" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 47.5 :RANK "266" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 47.32261 :RANK "267" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 47.2 :RANK "268" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 47.1 :RANK "269" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 46.13419 :RANK "270" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 46 :RANK "271" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 45.6 :RANK "272" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 45.2 :RANK "273" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 44.8 :RANK "274" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 44.3 :RANK "275" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 43.7 :RANK "276" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 43.2 :RANK "277" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 43.1 :RANK "278" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 43 :RANK "279" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 43 :RANK "280" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 42.8 :RANK "281" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 41.7 :RANK "282" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 41.7 :RANK "283" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 40.9 :RANK "284" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 40.5 :RANK "285" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 40.5 :RANK "286" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 40.3 :RANK "287" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 40.192112 :RANK "288" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 40.1 :RANK "289" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 39.6 :RANK "290" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 39.4 :RANK "291" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 38.5 :RANK "292" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 38.4 :RANK "293" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 38.3 :RANK "294" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 38.2 :RANK "295" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 38.2 :RANK "296" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 38 :RANK "297" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 37.6 :RANK "298" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 37 :RANK "299" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 36.8 :RANK "300" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 36 :RANK "301" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 35.5 :RANK "302" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 35.2 :RANK "303" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 34.94 :RANK "304" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 34.9 :RANK "305" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 34.9 :RANK "306" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 34.7 :RANK "307" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 34.6 :RANK "308" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 34.2 :RANK "309" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 33.9 :RANK "310" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 33.7 :RANK "311" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 33.5 :RANK "312" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 33.3 :RANK "313" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 33.2 :RANK "314" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 33.2 :RANK "315" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 33.2 :RANK "316" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 33.06162 :RANK "317" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 33 :RANK "318" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 33 :RANK "319" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 32.7 :RANK "320" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 32.6 :RANK "321" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 32.6 :RANK "322" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 32.5 :RANK "323" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 32.4 :RANK "324" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 32 :RANK "325" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 31.7 :RANK "326" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 31.6 :RANK "327" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 31.5 :RANK "328" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 30.6 :RANK "329" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 30.48 :RANK "330" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 30.4 :RANK "331" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 30.4 :RANK "332" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 30.2 :RANK "333" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 30 :RANK "334" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 29.5 :RANK "335" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 29.496372 :RANK "336" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 29.4 :RANK "337" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 29.4 :RANK "338" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 28.9 :RANK "339" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 28.6 :RANK "340" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 28.6 :RANK "341" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 28.307955 :RANK "342" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 28.307955 :RANK "343" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 28.2 :RANK "344" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 28 :RANK "345" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 28 :RANK "346" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 27.6 :RANK "347" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 27.5 :RANK "348" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 27.4 :RANK "349" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 27.3 :RANK "350" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 27.2 :RANK "351" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 27.2 :RANK "352" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 27.1 :RANK "353" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 27.1 :RANK "354" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 26.2 :RANK "355" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 26.1 :RANK "356" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 25.9 :RANK "357" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 25.9 :RANK "358" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 25.4 :RANK "359" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 25.2 :RANK "360" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 24.74271 :RANK "361" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 24.6 :RANK "362" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 23.5 :RANK "363" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 23 :RANK "364" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 23 :RANK "365" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 22.5 :RANK "366" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 22.5 :RANK "367" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 22.4 :RANK "368" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 22 :RANK "369" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 21.8 :RANK "370" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 21.7 :RANK "371" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 21.2 :RANK "372" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 21.2 :RANK "373" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 21.177462 :RANK "374" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 21.1 :RANK "375" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 21.1 :RANK "376" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 21 :RANK "377" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 20.8 :RANK "378" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 20.8 :RANK "379" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 20.7 :RANK "380" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 20.5 :RANK "381" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 20.4 :RANK "382" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 20.3 :RANK "383" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 20 :RANK "384" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 19.8 :RANK "385" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 19.7 :RANK "386" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 19.7 :RANK "387" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 19.3 :RANK "388" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 19.2 :RANK "389" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 19 :RANK "390" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 18.800632 :RANK "391" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 18.5 :RANK "392" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 18.3 :RANK "393" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 18.2 :RANK "394" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 17.6 :RANK "395" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 17.4 :RANK "396" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 17.3 :RANK "397" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 17.3 :RANK "398" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 16.98 :RANK "399" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 16.8 :RANK "400" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 16.3 :RANK "401" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 15.7 :RANK "402" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 15.4 :RANK "403" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 15.3 :RANK "404" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 15.235385 :RANK "405" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 15.235385 :RANK "406" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 15.1 :RANK "407" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 15.1 :RANK "408" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 14.98 :RANK "409" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 14.56 :RANK "410" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 14.5 :RANK "411" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 14.5 :RANK "412" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 14.4 :RANK "413" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 14.3 :RANK "414" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 14 :RANK "415" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 13.8 :RANK "416" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 13.7 :RANK "417" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 13.7 :RANK "418" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 13.36 :RANK "419" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 13.3 :RANK "420" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 13.3 :RANK "421" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 13.1 :RANK "422" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 13 :RANK "423" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 12.9 :RANK "424" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 12.9 :RANK "425" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 12.858554 :RANK "426" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 12.8 :RANK "427" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 12.5 :RANK "428" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 12.5 :RANK "429" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 12.3 :RANK "430" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 12.26 :RANK "431" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 12.1 :RANK "432" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 11.7 :RANK "433" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 11.5 :RANK "434" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 11.5 :RANK "435" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 11.5 :RANK "436" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 10.9 :RANK "437" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 10.8 :RANK "438" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 10.8 :RANK "439" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 10.6 :RANK "440" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 10.4 :RANK "441" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 10.2 :RANK "442" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 10.2 :RANK "443" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 10.2 :RANK "444" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 10.2 :RANK "445" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 10.1 :RANK "446" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 10 :RANK "447" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 9.74 :RANK "448" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 9.5 :RANK "449" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 9.5 :RANK "450" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 9.4 :RANK "451" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 9.2 :RANK "452" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 9.2 :RANK "453" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 9 :RANK "454" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 8.9 :RANK "455" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 8.8 :RANK "456" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 8.7 :RANK "457" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 8.6 :RANK "458" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 8.5 :RANK "459" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 8.3 :RANK "460" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 8.2 :RANK "461" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 7.9 :RANK "462" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 7.8 :RANK "463" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 7.72 :RANK "464" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 7.56 :RANK "465" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 7.56 :RANK "466" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 7.5 :RANK "467" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 7.4 :RANK "468" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 7.4 :RANK "469" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 7.3 :RANK "470" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 7.2 :RANK "471" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 7.1 :RANK "472" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 7 :RANK "473" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 6.9 :RANK "474" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 6.8 :RANK "475" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 6.8 :RANK "476" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 6.6 :RANK "477" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 6.5 :RANK "478" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 6.3 :RANK "479" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 6.3 :RANK "480" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 6.2 :RANK "481" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 6.2 :RANK "482" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 6.1 :RANK "483" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 5.9 :RANK "484" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 5.8 :RANK "485" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 5.7 :RANK "486" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 5.6 :RANK "487" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 5.6 :RANK "488" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 5.3 :RANK "489" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 5.3 :RANK "490" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 5.1 :RANK "491" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 5.1 :RANK "492" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 5.1 :RANK "493" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 5.1 :RANK "494" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 5.1 :RANK "495" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 4.9 :RANK "496" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 4.76 :RANK "497" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 4.7 :RANK "498" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 4.7 :RANK "499" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 4.6 :RANK "500" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 4.6 :RANK "501" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 4.5 :RANK "502" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 4.5 :RANK "503" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 4.5 :RANK "504" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 4.4 :RANK "505" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 4.3 :RANK "506" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 4.2 :RANK "507" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 4.2 :RANK "508" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 4.1 :RANK "509" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 4.1 :RANK "510" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 4 :RANK "511" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 3.9 :RANK "512" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 3.7 :RANK "513" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 3.5 :RANK "514" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 3.5 :RANK "515" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 3.4 :RANK "516" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 3.351229 :RANK "517" :DISPLAY-TYPE 'DF) 
(make-instance 'RANK-PLAYER
 :SCORE 3.12 :RANK "518" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 3.1 :RANK "519" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 3.1 :RANK "520" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 3.1 :RANK "521" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 3 :RANK "522" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 3 :RANK "523" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 2.7 :RANK "524" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 2.7 :RANK "525" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 2.6 :RANK "526" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 2.6 :RANK "527" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 2.6 :RANK "528" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 2.4 :RANK "529" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 2.32 :RANK "530" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 2.3 :RANK "531" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 2.2 :RANK "532" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 2.2 :RANK "533" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 2.2 :RANK "534" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 2.1 :RANK "535" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 2.1 :RANK "536" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 2.1 :RANK "537" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 2.04 :RANK "538" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 1.9 :RANK "539" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 1.9 :RANK "540" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 1.8 :RANK "541" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 1.8 :RANK "542" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 1.76 :RANK "543" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 1.6 :RANK "544" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 1.5 :RANK "545" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 1.5 :RANK "546" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 1.5 :RANK "547" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 1.5 :RANK "548" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 1.48 :RANK "549" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 1.4 :RANK "550" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 1.36 :RANK "551" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 1.3 :RANK "552" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 1.3 :RANK "553" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 1.3 :RANK "554" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 1.3 :RANK "555" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 1.28 :RANK "556" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 1.2 :RANK "557" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 1.2 :RANK "558" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 1.2 :RANK "559" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 1.2 :RANK "560" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 1.1 :RANK "561" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 1.1 :RANK "562" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 1.1 :RANK "563" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 1.1 :RANK "564" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 1.1 :RANK "565" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 1.06 :RANK "566" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.9 :RANK "567" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.9 :RANK "568" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.9 :RANK "569" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0.9 :RANK "570" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0.8 :RANK "571" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.8 :RANK "572" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.8 :RANK "573" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.8 :RANK "574" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0.8 :RANK "575" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0.8 :RANK "576" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0.7 :RANK "577" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.7 :RANK "578" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.7 :RANK "579" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.7 :RANK "580" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0.7 :RANK "581" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0.7 :RANK "582" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0.6 :RANK "583" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.6 :RANK "584" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0.6 :RANK "585" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0.6 :RANK "586" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0.6 :RANK "587" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0.56 :RANK "588" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.5 :RANK "589" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.5 :RANK "590" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.3 :RANK "591" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0.2 :RANK "592" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.1 :RANK "593" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0.1 :RANK "594" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "595" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "596" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "597" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "598" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "599" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "600" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "601" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "602" :DISPLAY-TYPE 'RB) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "603" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "604" :DISPLAY-TYPE 'QB) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "605" :DISPLAY-TYPE 'K) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "606" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "607" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "608" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "609" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "610" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "611" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "612" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "613" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "614" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "615" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "616" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "617" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "618" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "619" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "620" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "621" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "622" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "623" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "624" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "625" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "626" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "627" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "628" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "629" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "630" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "631" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "632" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "633" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "634" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "635" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE 0 :RANK "636" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE -0.3 :RANK "637" :DISPLAY-TYPE 'TE) 
(make-instance 'RANK-PLAYER
 :SCORE -0.4 :RANK "638" :DISPLAY-TYPE 'WR) 
(make-instance 'RANK-PLAYER
 :SCORE -23.98233 :RANK "639" :DISPLAY-TYPE 'DF) )